/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.gui;

/**
 *
 * @author Manuel
 */
public class ventanaIngresoRetiro extends javax.swing.JFrame {

    /**
     * Creates new form ventanaBanco3
     */
    public ventanaIngresoRetiro() {
        initComponents();
        //inicializarIngreso();
        //inicializarRetiro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleIng = new javax.swing.JLabel();
        lblTitleIngreso = new javax.swing.JLabel();
        jTFRetira = new javax.swing.JTextField();
        btnIngresa = new javax.swing.JButton();
        lblTitleRet = new javax.swing.JLabel();
        lblTitleRetiro = new javax.swing.JLabel();
        jTFIngreso = new javax.swing.JTextField();
        btnRetira = new javax.swing.JButton();
        lblbanOrigen = new javax.swing.JLabel();
        lblbanDestino = new javax.swing.JLabel();
        jTFIbanDestinoRet = new javax.swing.JTextField();
        jTFIbanOrigenRet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblbanOrigenIn = new javax.swing.JLabel();
        lblbanDestinoIn = new javax.swing.JLabel();
        jTFIbanOrigenIng = new javax.swing.JTextField();
        jTFIbanDestinoIng = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THE BANK");

        lblTitleIng.setText("INGRESO A CUENTA");

        lblTitleIngreso.setText("Cuanto desea ingresar:");

        btnIngresa.setText("Ingresa");

        lblTitleRet.setText("RETIRO DE CUENTA");

        lblTitleRetiro.setText("Cuanto desea retirar:");

        btnRetira.setText("Retira");

        lblbanOrigen.setText("Iban Origen");

        lblbanDestino.setText("Iban Destino");

        lblbanOrigenIn.setText("Iban Origen");

        lblbanDestinoIn.setText("Iban Destino");

        jTFIbanDestinoIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIbanDestinoIngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblbanDestino)
                                            .addComponent(lblbanOrigen)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(lblTitleRetiro)))
                                .addGap(9, 9, 9))
                            .addComponent(lblTitleIngreso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTFIbanOrigenRet, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addGap(79, 79, 79))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTFIbanDestinoRet, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFRetira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRetira))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFIbanDestinoIng)
                                    .addComponent(jTFIbanOrigenIng)
                                    .addComponent(jTFIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIngresa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleRet)
                            .addComponent(lblTitleIng))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblbanDestinoIn)
                    .addComponent(lblbanOrigenIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitleIng)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblbanOrigenIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTFIbanOrigenIng, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIbanDestinoIng, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbanDestinoIn)
                    .addComponent(btnIngresa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblTitleRet)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIbanOrigenRet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbanOrigen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIbanDestinoRet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbanDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRetira)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleRetiro)
                    .addComponent(jTFRetira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFIbanDestinoIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIbanDestinoIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIbanDestinoIngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaIngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaIngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaIngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaIngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaIngresoRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresa;
    private javax.swing.JButton btnRetira;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFIbanDestinoIng;
    private javax.swing.JTextField jTFIbanDestinoRet;
    private javax.swing.JTextField jTFIbanOrigenIng;
    private javax.swing.JTextField jTFIbanOrigenRet;
    private javax.swing.JTextField jTFIngreso;
    private javax.swing.JTextField jTFRetira;
    private javax.swing.JLabel lblTitleIng;
    private javax.swing.JLabel lblTitleIngreso;
    private javax.swing.JLabel lblTitleRet;
    private javax.swing.JLabel lblTitleRetiro;
    private javax.swing.JLabel lblbanDestino;
    private javax.swing.JLabel lblbanDestinoIn;
    private javax.swing.JLabel lblbanOrigen;
    private javax.swing.JLabel lblbanOrigenIn;
    // End of variables declaration//GEN-END:variables

    private void inicializarRetiro() {
        lblTitleIng.setVisible(false);
        lblTitleIngreso.setVisible(false);
        jTFIngreso.setVisible(false);
        btnIngresa.setVisible(false);
        btnIngresa.setEnabled(false);
    }

    private void inicializarIngreso() {
        lblTitleRet.setVisible(false);
        lblTitleRetiro.setVisible(false);
        jTFRetira.setVisible(false);
        btnRetira.setVisible(false);
        btnRetira.setEnabled(false);
    }
}
